################################################################################
# Copyright 2025 Confluent Inc.
################################################################################
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confluent_udf_shim/proto/api/extractor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,confluent_udf_shim/proto/api/extractor.proto\x12\x16\x66link.udf.extractor.v1\"O\n\x05\x45rror\x12/\n\x04\x63ode\x18\x01 \x01(\x0e\x32!.flink.udf.extractor.v1.ErrorCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"U\n\x11\x45xtractionRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x19\n\x11plugin_version_id\x18\x02 \x01(\t\x12\x12\n\nclass_name\x18\x03 \x01(\t\"M\n\tSignature\x12\x15\n\rargumentTypes\x18\x01 \x03(\t\x12\x12\n\nreturnType\x18\x02 \x01(\t\x12\x15\n\rargumentNames\x18\x03 \x03(\t\"\xaa\x01\n\x12\x45xtractionResponse\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1d.flink.udf.extractor.v1.Error\x12\x35\n\nsignatures\x18\x02 \x03(\x0b\x32!.flink.udf.extractor.v1.Signature\x12\x18\n\x10is_deterministic\x18\x03 \x01(\x08\x12\x15\n\rfunction_kind\x18\x04 \x01(\t*\xde\x01\n\tErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1d\n\x19GENERAL_FAILED_EXTRACTION\x10\x01\x12\x17\n\x13USER_CODE_NOT_FOUND\x10\x02\x12\x17\n\x13NOT_SCALAR_FUNCTION\x10\x03\x12 \n\x1cNO_PUBLIC_NO_ARG_CONSTRUCTOR\x10\x04\x12\x19\n\x15TYPE_EXTRACTION_ERROR\x10\x05\x12\x1a\n\x16NOT_SUPPORTED_FUNCTION\x10\x06\x12\x1a\n\x16\x43LASS_NOT_SERIALIZABLE\x10\x07\x42}\n#io.confluent.flink.udf.extractor.v1P\x01ZTgithub.com/confluentinc/flink/cc-flink-extensions/cc-flink-udf-adapter-api/api/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'confluent_udf_shim.proto.api.extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#io.confluent.flink.udf.extractor.v1P\001ZTgithub.com/confluentinc/flink/cc-flink-extensions/cc-flink-udf-adapter-api/api/v1;v1'
  _globals['_ERRORCODE']._serialized_start=493
  _globals['_ERRORCODE']._serialized_end=715
  _globals['_ERROR']._serialized_start=72
  _globals['_ERROR']._serialized_end=151
  _globals['_EXTRACTIONREQUEST']._serialized_start=153
  _globals['_EXTRACTIONREQUEST']._serialized_end=238
  _globals['_SIGNATURE']._serialized_start=240
  _globals['_SIGNATURE']._serialized_end=317
  _globals['_EXTRACTIONRESPONSE']._serialized_start=320
  _globals['_EXTRACTIONRESPONSE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
